[project]
name = "pagerduty_mcp_server"
version = "v2.2.0"
description = "MCP server for LLM agents to interact with PagerDuty SaaS"
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
keywords = ["pagerduty", "mcp", "llm", "api", "server"]
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "fastmcp>=2.5.1",
    "pagerduty>=1.0.0",
]

[project.scripts]
pagerduty-mcp-server = "pagerduty_mcp_server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
